/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador;

import javax.swing.ImageIcon;

/**
 *
 * @author KillerCoffeBR
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        
        //Altera o icone no topo da janela
        
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/car.png")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_TelaCliente = new javax.swing.JButton();
        Btn_TelaAutos = new javax.swing.JButton();
        Btn_TelaVagas = new javax.swing.JButton();
        Btn_TelaNotaF1 = new javax.swing.JButton();
        Btn_TelaLocacao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROParking - Início");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_TelaCliente.setText("Tela Cliente");
        Btn_TelaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TelaClienteActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_TelaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 129, 42));

        Btn_TelaAutos.setText("Tela veículos");
        Btn_TelaAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TelaAutosActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_TelaAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 42));

        Btn_TelaVagas.setText("Tela Vagas");
        Btn_TelaVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TelaVagasActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_TelaVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 129, 42));

        Btn_TelaNotaF1.setText("Tela Nota Fiscal");
        Btn_TelaNotaF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TelaNotaF1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_TelaNotaF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 129, 42));

        Btn_TelaLocacao.setText("Tela Locação");
        Btn_TelaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TelaLocacaoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_TelaLocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 129, 42));

        jLabel2.setFont(new java.awt.Font("DialogInput", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Início");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_TelaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TelaClienteActionPerformed
        // TODO add your handling code here:
        ClienteTela clitela;
        clitela = new ClienteTela();
        clitela.setVisible(true);
        clitela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Btn_TelaClienteActionPerformed

    private void Btn_TelaAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TelaAutosActionPerformed
    AutomovelTela autotela;
    autotela = new  AutomovelTela();
    autotela.setVisible(true);
    autotela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Btn_TelaAutosActionPerformed

    private void Btn_TelaVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TelaVagasActionPerformed
    VagasTela vagatela;
    vagatela = new  VagasTela();
    vagatela.setVisible(true);
    vagatela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Btn_TelaVagasActionPerformed

    private void Btn_TelaNotaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TelaNotaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_TelaNotaF1ActionPerformed

    private void Btn_TelaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TelaLocacaoActionPerformed
        // TODO add your handling code here:
        LocacaoTela locacaotela;
        locacaotela = new LocacaoTela();
        locacaotela.setVisible(true);
        locacaotela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Btn_TelaLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_TelaAutos;
    private javax.swing.JButton Btn_TelaCliente;
    private javax.swing.JButton Btn_TelaLocacao;
    private javax.swing.JButton Btn_TelaNotaF1;
    private javax.swing.JButton Btn_TelaVagas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
