/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador;

import dao.LocacaoDAO;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Locacao;
import modelo.Vaga;

/**
 *
 * @author KillerCoffeBR
 */
public class LocacaoTela extends javax.swing.JFrame {

    /**
     * Creates new form LocacaoTela
     */
    public LocacaoTela() {
        
        //Altera o icone no topo da janela
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/car.png")).getImage());
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txt_Saida = new javax.swing.JTextField();
        txt_Vaga = new javax.swing.JTextField();
        txt_Cpf = new javax.swing.JTextField();
        txt_Entrada = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROParking - Locação");
        setPreferredSize(new java.awt.Dimension(550, 375));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(542, 202));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 27, 53, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 73, 53, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Saída:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 119, 53, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Vaga:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 30, 53, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Entrada");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 80, 61, 30);

        txt_Id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Id);
        txt_Id.setBounds(89, 34, 156, 20);
        jPanel1.add(txt_Saida);
        txt_Saida.setBounds(89, 126, 156, 20);
        jPanel1.add(txt_Vaga);
        txt_Vaga.setBounds(480, 40, 156, 20);
        jPanel1.add(txt_Cpf);
        txt_Cpf.setBounds(89, 80, 156, 20);
        jPanel1.add(txt_Entrada);
        txt_Entrada.setBounds(480, 80, 156, 20);

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/aceitar.png"))); // NOI18N
        BtnSalvar.setContentAreaFilled(false);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalvar);
        BtnSalvar.setBounds(200, 250, 66, 62);

        BtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        BtnPesquisar.setContentAreaFilled(false);
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPesquisar);
        BtnPesquisar.setBounds(290, 250, 70, 62);

        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtnExcluir.setBorderPainted(false);
        BtnExcluir.setContentAreaFilled(false);
        jPanel1.add(BtnExcluir);
        BtnExcluir.setBounds(380, 250, 67, 65);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/148250_Queue_Assist-1024x576.jpg"))); // NOI18N
        jPanel1.add(fundo);
        fundo.setBounds(-170, 0, 1090, 576);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(671, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        {

            Locacao locacao = new Locacao();
            Vaga vaga = new Vaga();

            if (txt_Cpf.getText().isEmpty() || txt_Vaga.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Preencher todos os campos!");
            }
            else
            {
                //                cliente.setCpf(txt_Id.getText());
                //                cliente.setRg(txt_Cpf.getText());
                //                cliente.setTelefone(txt_Saida.getText());
                //                cliente.setNome(txt_Vaga.getText());
                Timestamp Entrada = new Timestamp(System.currentTimeMillis());
                locacao.setCpf(txt_Cpf.getText());
                locacao.setVaga(Integer.parseInt(txt_Vaga.getText()));
                locacao.setEntrada(Entrada);

                vaga.setStatus(Boolean.parseBoolean("1"));

                LocacaoDAO dao = new LocacaoDAO();

                Boolean deucerto = dao.inserir(locacao);

                if (deucerto == true)
                {
                    JOptionPane.showMessageDialog(rootPane, "Você deu entrada na locação!");

                    txt_Vaga.setText("");
                    txt_Id.setText("");
                    txt_Saida.setText("");
                    txt_Cpf.setText("");
                    txt_Entrada.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Parece que tem algo errado!");
                }

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocacaoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Cpf;
    private javax.swing.JTextField txt_Entrada;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Saida;
    private javax.swing.JTextField txt_Vaga;
    // End of variables declaration//GEN-END:variables
}
